"""
01_corpus.py — Corpus and project management
============================================

Create projects, create corpora, import transcripts and documents.
This is the entry point for every new research project.
"""

from __future__ import annotations

from pathlib import Path

import streamlit as st

st.set_page_config(page_title="Corpus | Thematic Analysis", layout="wide")

st.title("Corpus management")

tab_projects, tab_import, tab_sources = st.tabs(["Projects", "Import", "Sources"])

# ── Projects ──────────────────────────────────────────────────────────────────
with tab_projects:
    st.subheader("Active project")

    col_new, col_select = st.columns(2)

    with col_new:
        with st.form("new_project"):
            st.markdown("**Create project**")
            name = st.text_input("Name", placeholder="Urban pedagogy study 2026")
            description = st.text_area(
                "Research question",
                placeholder="How do community educators navigate institutional exclusion?",
                height=80,
            )
            submitted = st.form_submit_button("Create")
            if submitted and name:
                st.success(f"Project '{name}' created.")
                st.session_state["active_project_id"] = f"proj-{name[:8].lower()}"
                st.session_state["active_project_name"] = name

    with col_select:
        st.markdown("**Select existing project**")
        # Placeholder — replace with DB query
        projects = st.session_state.get("demo_projects", ["Urban pedagogy 2026", "Field notes corpus"])
        chosen = st.selectbox("Project", projects)
        if st.button("Activate"):
            st.session_state["active_project_name"] = chosen
            st.success(f"Active project: {chosen}")

    if st.session_state.get("active_project_name"):
        st.info(f"Active project: **{st.session_state['active_project_name']}**")

# ── Import ────────────────────────────────────────────────────────────────────
with tab_import:
    st.subheader("Import material")

    import_type = st.radio(
        "Source type",
        ["Transcript (.transcript.json)", "Document (.txt / .docx / .pdf)"],
        horizontal=True,
    )

    uploaded = st.file_uploader(
        "Upload file",
        type=["json", "txt", "docx", "pdf"] if "Document" in import_type else ["json"],
        help=(
            "For transcripts: upload the .transcript.json file produced by the "
            "audio-transcriber project. Speaker labels, timestamps, and "
            "confidence scores are preserved automatically."
        ),
    )

    corpus_name = st.text_input("Corpus name", placeholder="Phase 1 interviews")

    include_interviewer = st.checkbox(
        "Include INTERVIEWER turns",
        value=False,
        help=(
            "By default, only INTERVIEWEE turns are imported for thematic analysis. "
            "Enable this to import all speaker turns."
        ),
    )

    min_words = st.slider(
        "Minimum words per segment",
        min_value=1,
        max_value=20,
        value=3,
        help="Segments shorter than this are skipped (removes filler utterances).",
    )

    if uploaded and st.button("Import"):
        with st.spinner("Importing…"):
            # Save uploaded file to a temp path.
            tmp_path = Path(f"/tmp/{uploaded.name}")
            tmp_path.write_bytes(uploaded.getvalue())

            from thematic.infrastructure.importers.transcript_importer import (
                TranscriptJsonImporter,
            )

            importer = TranscriptJsonImporter(
                min_words=min_words,
                include_interviewer=include_interviewer,
            )

            if not importer.can_import(tmp_path):
                st.error(
                    f"'{uploaded.name}' is not a valid .transcript.json file. "
                    "Please upload a file generated by the audio-transcriber project."
                )
            else:
                try:
                    source, segments = importer.import_transcript(tmp_path, corpus_id="demo")
                    st.success(
                        f"Imported **{source.title}**: {len(segments)} segments "
                        f"({source.import_metadata.get('language', '?')} · "
                        f"{float(source.import_metadata.get('duration_s', 0)) / 60:.1f} min)"
                    )
                    # Show preview
                    with st.expander("Preview first 5 segments"):
                        for seg in segments[:5]:
                            speaker_label = f"**{seg.speaker}**" if seg.speaker else ""
                            time = f"`{seg.start_s:.0f}s`" if seg.start_s else ""
                            st.markdown(f"{speaker_label} {time}  \n{seg.text}")
                            st.divider()
                except Exception as exc:
                    st.error(f"Import failed: {exc}")

# ── Sources ───────────────────────────────────────────────────────────────────
with tab_sources:
    st.subheader("Imported sources")
    st.info("Sources will appear here once a project is active and material has been imported.")
    st.caption(
        "Each source shows: title · speaker turn count · word count · "
        "embedding status · import date"
    )
